config/routes.rb
Rails.application.routes.draw do
  

  root 'home#index'

  resources :users, :sessions

  namespace :admin do
    resources :roles, :dashboard
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
    has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    belongs_to :role
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
  end

  def show
  end
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::ApplicationController
  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    @role.delete_flag = 0
    
    if @role.save
      redirect_to admin_roles_path, notice: 'Role was save successfull created'
    else
      render 'new'
    end
    
  end

  def edit
  end

  def update
  end

  def index
    @roles = Role.where(delete_flag: 0).all
  end

  def show
  end

  def destroy
  end
  
  def role_params
      params.require(:role).permit(:name, :delete_flag)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end
  
  def new
  end

  def create
    byebug
    @user = User.find_by(name: params[:name]).try(:authenticate, params[:password])  
    if @user.nil?
      flash.now[:error] = "Invalid Username / Password combination"
      redirect_to root_path
    else
      sign_in @user

      if is_admin
        redirect_to admin_dashboard_index_path
      else
        redirect_to root_path
      end
    end
    
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @memberRole = Role.find_by(name: "Free")
    @user.role_id = @memberRole.id
    @user.delete_flag = 0
    byebug
  	if @user.save
  		redirect_to root_path, notice: 'User was save successfull created'
  	else
  		render action: 'new'
  	end
  end

  def edit
  end

  def update
  end

  def index
  end

  def show
  end

  def destroy
  end
  
  private 
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def sign_in(user)
        session[:user_id] = user.id
        self.current_user = user
    end
    
    def current_user=(user)
        @current_user = user
    end
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    def signed_in?
        !current_user.nil?
    end
    
    def sign_out
        session[:user_id] = nil
        self.current_user = nil
    end
    
    def current_user?(user)
        user == current_user
    end
    
    def deny_access
        redirect_to root_path, :notice => "Pleas sign in to access this page."
    end
    
    def is_admin
        if self.current_user.role.name == "Admin"
            true
        else
            false
        end
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Admin::Dashboard#index</h1>
<p>Find me in app/views/admin/dashboard/index.html.erb</p>

app/views/admin/dashboard/show.html.erb
<h1>Admin::Dashboard#show</h1>
<p>Find me in app/views/admin/dashboard/show.html.erb</p>

app/views/admin/roles/create.html.erb
<h1>Admin::Roles#create</h1>
<p>Find me in app/views/admin/roles/create.html.erb</p>

app/views/admin/roles/destroy.html.erb
<h1>Admin::Roles#destroy</h1>
<p>Find me in app/views/admin/roles/destroy.html.erb</p>

app/views/admin/roles/edit.html.erb
<h1>Admin::Roles#edit</h1>
<p>Find me in app/views/admin/roles/edit.html.erb</p>

app/views/admin/roles/index.html.erb
<h1>List Roles</h1>

<ul>
    <% @roles.each do |ro| %>
        <li><%= ro.name %> - <%= link_to "Delete", admin_role_path(ro), method: :delete, data: {confirm: 'Bạn có muốn xóa Role này không ?'} %></li>
    <% end %>
</ul>
<br/>
<%= link_to "Add new role", new_admin_role_path %>

app/views/admin/roles/new.html.erb
<h1>Add role</h1>
<%= form_for [:admin, @role] do |f| %>
    Name: <%= f.text_field :name %>
    <br/>
    <%= f.submit "OK" %>
<% end %>

app/views/admin/roles/show.html.erb
<h1>Admin::Roles#show</h1>
<p>Find me in app/views/admin/roles/show.html.erb</p>

app/views/admin/roles/update.html.erb
<h1>Admin::Roles#update</h1>
<p>Find me in app/views/admin/roles/update.html.erb</p>

app/views/home/index.html.erb
  <div class="container">
    
      <div class="row">
        <div class="col s8">
          <div class="col s12">
              <div class="card grey lighten-2">
                <div class="card-content black-text">                  
                  <p>-[Update 22-12-2016] <span id="news_title">Sửa lỗi getlink</span> <span id="new_news"></span></p>
                  <p>-[Update 29-11-2016] <span id="news_title">4Share.VN hiện tại chỉ dành cho VIP & Premium</span> <span id="new_news"/></p>
                  <p>-[Update 02-10-2016] <span id="news_title">Hỗ trợ get nhiều link cùng lúc </span><span id="new_news"/></p>
                  <p>-[Update 02-10-2016] <span id="news_title">Filefactory Online Now </span> <span id="new_news"/></p>
                  <p>-[Update 14-09-2016] <span id="news_title">Keep2Share  Turbobit Online Now </span><span id="new_news"/></p>
                  <p>Hãy share & Like để giúp team phát triển nhiều host hơn nữa</p>
                </div>              
              </div>
          </div>
          <div class="col s12">
              <div class="card teal">
                <div class="card-content white-text"> 
                  <!-- <span class="card-title">Leech link</span> -->
                  <form>                    
                      <div>                                           
                        <input id="linkurl" type="text" class="validate" placeholder="Input your link">
                      </div>
                      <div>                                                
                        <input id="linkpassword" type="password" class="validate" placeholder="password if any">
                      </div>
                      <p>                        
                        <a class="waves-effect waves-light btn">GET LINK</a>
                      </p>
                  </form>
                </div>
              </div>
          </div>          
        </div>
        <div class="col s4">
          
            <div class="col s12">
              <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                  <% if @current_user %>
                    <span class="card-title"><span class="welcomeuser">Hi! <%= @current_user.name %></span></span>
                    <p>Loại tài khoản: <span class="member_class"><%= @current_user.role.name %> Member</span></p>
                    <p>Số ngày còn lại: 30 ngày 2 giờ</p>
                  <% else %>
                    <span class="card-title">Login</span>
                    <%= form_tag sessions_path do %>
                      <div>                                                                      
                        <%= text_field_tag :name, "", class: 'validate', placeholder: 'Username' %>
                      </div>
                      <div>                                                                      
                        <%= password_field_tag :password, "", class: 'validate', placeholder: 'Password' %>
                      </div>
                      <p>
                        <input type="checkbox" class="filled-in" id="filled-in-box" checked="checked" />
                        <label for="filled-in-box">Remember Me</label>
                        &nbsp;&nbsp;&nbsp;<%= submit_tag "LOGIN", class:'waves-effect waves-light btn' %>
                      </p>
                    <% end %>
                  <% end %>
                </div>
                <!-- <div class="card-action">
                  <a href="#">This is a link</a>
                  <a href="#">This is a link</a>
                </div> -->
              </div>
            </div>
          
        </div>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Getlink - xiinh club</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "partials/header" %>
<%= yield %>
<%= render "partials/footer" %>

<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
</body>
</html>

app/views/partials/_footer.html.erb
<footer class="page-footer blue-grey darken-1">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="orange-text text-lighten-3" href="#">YLE</a>
      </div>
    </div>
  </footer>

app/views/partials/_header.html.erb
<nav class="cyan darken-3" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">xiinh - Get Links</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">Register</a></li>
      </ul>
       <ul class="right hide-on-med-and-down">
        <li><a href="#">Hosts Support</a></li>
      </ul>
       <ul class="right hide-on-med-and-down">
        <li><a href="#">Upgrade Vip Member</a></li>
      </ul>
       <ul class="right hide-on-med-and-down">
        <li><a href="#">News</a></li>
      </ul>
       <ul class="right hide-on-med-and-down">
        <li><a href="#">Home</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">Home</a></li>
        <li><a href="#">News</a></li>
        <li><a href="#">Upgrade Vip Member</a></li>
        <li><a href="#">Hosts Support</a></li>
        <li><a href="#">Register</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="container">    
      <br/><br/><br/><br/><br/><br/>
      <div class="row">
        <div class="col s12 m8 offset-m2">    
            <div class="col s12">
              <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                  <span class="card-title">Đăng ký thành viên</span>
                  <br/>
                  
                  <%= form_for @user do |f| %>
                    <div>                                                                 
                      <%= f.text_field :name, class:'validate', placeholder:'Tên đăng nhập' %>
                    </div>
                    <div>                                                                 
                      <%= f.text_field :email, class:'validate', placeholder:'Email' %>
                    </div>
                    <div>                                                                 
                      <%= f.password_field :password, class:'validate', placeholder:'Mật khẩu' %>
                    </div>
                    <p>
                      <%= f.submit "ĐĂNG KÝ", class:'waves-effect waves-light btn' %>
                    </p>
                  <% end %>
                </div>
              </div>
            </div>
        </div>
      </div>
      <br/>
      <br/><br/><br/><br/>
  	</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>